version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_CONTENT_PAT }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - quantco/ci
    registries:
      - github
    groups:
      gh-actions:
        patterns:
          - "*"
