# Copyright (c) QuantCo 2023-2024
# SPDX-License-Identifier: BSD-3-Clause

from .array import Array, asarray
from .dtypes import DType
from ._typed_array.onnx import (
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    uint64,
    float16,
    float32,
    float64,
    string,
    bool_ as bool,
)
from ._typed_array.masked_onnx import (
    nint8,
    nint16,
    nint32,
    nint64,
    nuint8,
    nuint16,
    nuint32,
    nuint64,
    nfloat16,
    nfloat32,
    nfloat64,
    nstring,
    nbool,
)
from .funcs import (
    astype,
    arange,
    concat,
    empty,
    empty_like,
    eye,
    ones,
    ones_like,
    full,
    full_like,
    reshape,
    all,
    zeros,
    zeros_like,
    linspace,
    where,
    sum,
)
from .elementwise import (
    abs,
    acos,
    acosh,
    asin,
    asinh,
    atan,
    atanh,
    ceil,
    exp,
    expm1,
    floor,
    isnan,
    isfinite,
    isinf,
)
from .binary_functions import add, equal, maximum
from .infos import finfo, iinfo
from .namespace_info import __array_namespace_info__
from .constants import e, inf, nan, pi, newaxis

_default_int = int64
_default_float = float64

__all__ = [
    "__array_namespace_info__",
    "Array",
    "DType",
    # ONNX data types
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float16",
    "float32",
    "float64",
    "string",
    "bool",
    # masked ONNX data types
    "nint8",
    "nint16",
    "nint32",
    "nint64",
    "nuint8",
    "nuint16",
    "nuint32",
    "nuint64",
    "nfloat16",
    "nfloat32",
    "nfloat64",
    "nbool",
    "nstring",
    "abs",
    "acos",
    "acos",
    "acosh",
    "add",
    "all",
    "arange",
    "asarray",
    "asin",
    "asinh",
    "astype",
    "atan",
    "atanh",
    "concat",
    "ceil",
    "e",
    "empty",
    "empty_like",
    "equal",
    "exp",
    "expm1",
    "eye",
    "finfo",
    "floor",
    "full",
    "full_like",
    "iinfo",
    "inf",
    "isfinite",
    "isinf",
    "isnan",
    "linspace",
    "maximum",
    "nan",
    "newaxis",
    "ones",
    "ones_like",
    "pi",
    "reshape",
    "sum",
    "where",
    "zeros",
    "zeros_like",
]
