# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: ndonnx
  version: ${{ env.get('GIT_DESCRIBE_TAG') | trim('v') }}${{ ('.post' + env.get('GIT_DESCRIBE_NUMBER') + '+' + env.get('GIT_DESCRIBE_HASH')) if env.get_default('GIT_DESCRIBE_NUMBER', '0') != '0' }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python>=3.9
    - pip
    - setuptools-scm
  run:
    - python>=3.9
    - numpy
    - onnx>=1.15
    - spox>=0.10

tests:
  - python:
      imports:
        - ndonnx
      pip_check: true

about:
  homepage: https://github.com/quantco/ndonnx
  license: LicenseRef-QuantCo
  summary: "ONNX-backed array library that is compliant with the Array API standard"
