name: Documentation
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
        with:
          auth-host: https://conda.prod.quantco.cloud
          auth-conda-token: ${{ secrets.QUETZ_API_KEY }}
          environments: docs
      - name: Install package
        run: pixi run -e docs postinstall
      - name: Build docs
        run: pixi run docs
      - name: Upload html
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
      - name: Publish docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
