name: Package
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Build conda package
        uses: quantco/rattler-build-action@v0.8.10
        with:
          quetz-api-key: ${{ secrets.QUETZ_API_KEY }}
          upload-quetz: ${{ startsWith(github.ref, 'refs/tags/') }}
